// <auto-generated />
using ExamenT1DSWAxelDelSolarLeon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenT1DSWAxelDelSolarLeon.Migrations
{
    [DbContext(typeof(DbContextExamen))]
    [Migration("20251126020655_DatosPredefinidos")]
    partial class DatosPredefinidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = 1,
                            CodigoCurso = "MAT01",
                            Creditos = 4,
                            HorasSemanales = 5,
                            NivelAcademicoId = 1
                        },
                        new
                        {
                            CursoId = 2,
                            CodigoCurso = "PROG01",
                            Creditos = 3,
                            HorasSemanales = 4,
                            NivelAcademicoId = 2
                        },
                        new
                        {
                            CursoId = 3,
                            CodigoCurso = "BD01",
                            Creditos = 3,
                            HorasSemanales = 3,
                            NivelAcademicoId = 2
                        },
                        new
                        {
                            CursoId = 4,
                            CodigoCurso = "IA01",
                            Creditos = 5,
                            HorasSemanales = 5,
                            NivelAcademicoId = 3
                        });
                });

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("NivelesAcademicos");

                    b.HasData(
                        new
                        {
                            NivelAcademicoId = 1,
                            Descripcion = "Básico",
                            Orden = 1
                        },
                        new
                        {
                            NivelAcademicoId = 2,
                            Descripcion = "Intermedio",
                            Orden = 2
                        },
                        new
                        {
                            NivelAcademicoId = 3,
                            Descripcion = "Avanzado",
                            Orden = 3
                        });
                });

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.Curso", b =>
                {
                    b.HasOne("ExamenT1DSWAxelDelSolarLeon.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
