// <auto-generated />
using ExamenT1DSWAxelDelSolarLeon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenT1DSWAxelDelSolarLeon.Migrations
{
    [DbContext(typeof(DbContextExamen))]
    [Migration("20251126014600_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("NivelesAcademicos");
                });

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.Curso", b =>
                {
                    b.HasOne("ExamenT1DSWAxelDelSolarLeon.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("ExamenT1DSWAxelDelSolarLeon.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
